name: CI (Build) 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "PACKAGE_VERSION=2.10.$((610+GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Docker Image'
        run: |
              docker build . --tag ghcr.io/octopussolutionsengineering/octofx-frontend:env.PACKAGE_VERSION
              docker push ghcr.io/octopussolutionsengineering/octofx-frontend:env.PACKAGE_VERSION
